const { build } = require('esbuild');
const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const outdir = path.resolve(__dirname, '../assets/wsockets');
const outfile = path.join(outdir, 'WSocketClient.js');
const dtsOutfile = path.join(outdir, 'WSocketClient.d.ts');
const tempDtsDir = path.resolve(__dirname, 'temp_dts');

// 确保输出目录存在
fs.mkdirSync(outdir, { recursive: true });

build({
    entryPoints: ['wsockets/WSocketClient.ts'],
    bundle: true,
    outfile: outfile,
    platform: 'browser',
    target: 'es2015',
    minify: true,
}).then(() => {
    console.log(`✅ Bundle created at ${outfile}`);
    console.log('⏳ Generating declaration files via tsc...');
    try {
        // 1. 清理临时目录
        if (fs.existsSync(tempDtsDir)) {
            fs.rmSync(tempDtsDir, { recursive: true, force: true });
        }

        // 2. 直接调用 tsc，不再依赖 tsconfig.d.ts.json
        const wsocketsDir = path.resolve(__dirname);
        const filesToCompile = fs.readdirSync(wsocketsDir)
            .filter(f => f.endsWith('.ts') || f.endsWith('.d.ts'))
            .map(f => path.join('wsockets', f));
        
        const tscCommand = `npx tsc ${filesToCompile.join(' ')} --declaration --emitDeclarationOnly --outDir ${tempDtsDir} --target es2015 --lib es2015,dom --strict false --moduleResolution node --skipLibCheck`;
        execSync(tscCommand);
        console.log(`✅ Raw declaration files created in ${tempDtsDir}`);

        console.log('⏳ Optimizing and consolidating declaration file...');
        
        // 3. 定义 TypeScript 内置类型集合，用于过滤
        const builtinTypes = new Set(['undefined', 'null', 'void', 'never', 'unknown', 'any', 'boolean', 'number', 'string', 'object', 'symbol', 'bigint']);
        
        // 找到所有声明的类型
        const declarations = new Set();
        const dtsFiles = fs.readdirSync(tempDtsDir).filter(f => f.endsWith('.d.ts'));

        for (const file of dtsFiles) {
            const content = fs.readFileSync(path.join(tempDtsDir, file), 'utf8');
            const declarationRegex = /export declare (?:class|interface|const|enum|type)\s+(\w+)/g;
            let match;
            while ((match = declarationRegex.exec(content)) !== null) {
                const typeName = match[1];
                // 过滤掉内置类型
                if (!builtinTypes.has(typeName)) {
                    declarations.add(typeName);
                }
            }
        }

        // 4. 读取 WSocketClient.d.ts 的内容并进行清理
        let clientDtsContent = fs.readFileSync(path.join(tempDtsDir, 'WSocketClient.d.ts'), 'utf8');
        clientDtsContent = clientDtsContent.replace(/^import[\s\S]*?from\s*['"].*?['"];\n/gm, '');

        const clientRegex = /(export declare class WSocketClient\s*\{[\s\S]*?\n\})/;
        const clientMatch = clientDtsContent.match(clientRegex);
        if (!clientMatch) {
            throw new Error("Could not find 'export declare class WSocketClient' in the generated d.ts file.");
        }
        let clientDeclaration = clientMatch[0].replace('export declare', 'declare');
        clientDeclaration = clientDeclaration.replace(/^\s*private\s+[\s\S]*?;\n/gm, '');

        // 强制将内部依赖替换为 any，使用更精确的匹配避免误替换 WSocketClient
        clientDeclaration = clientDeclaration.replace(/: WSocketProtoBuf\b/g, ': any');
        clientDeclaration = clientDeclaration.replace(/: WSocket\b(?![C])/g, ': any');

        // 5. 为其他类型创建 'any' 存根
        // 过滤掉 WSocketClient 和所有 TypeScript 内置类型
        const stubs = [];
        for (const name of declarations) {
            if (name !== 'WSocketClient' && !builtinTypes.has(name)) {
                stubs.push(`declare type ${name} = any;`);
            }
        }
        
        // 6. 组合最终的 d.ts 内容
        const finalDtsContent = `/**
 * Auto-generated by build.js
 * Contains a simplified global declaration for WSocketClient.
 * All internal dependencies are replaced with 'any'.
 */

${stubs.join('\n')}

${clientDeclaration}
`;
        
        // 7. 清理 assets 目录中旧的 .d.ts 文件
        const existingDts = fs.readdirSync(outdir).filter(f => f.endsWith('.d.ts'));
        for (const file of existingDts) {
            fs.unlinkSync(path.join(outdir, file));
        }

        fs.writeFileSync(dtsOutfile, finalDtsContent);
        console.log(`✅ Final declaration file created at ${dtsOutfile}`);

    } catch (error) {
        const errorMessage = error.stdout ? error.stdout.toString() : error.message;
        console.error('❌ Failed to generate or optimize declaration file:', errorMessage);
        process.exit(1);
    } finally {
        // 8. 清理临时目录
        if (fs.existsSync(tempDtsDir)) {
            fs.rmSync(tempDtsDir, { recursive: true, force: true });
            console.log('✅ Temporary files cleaned up.');
        }
    }
}).catch((e) => {
    console.error('❌ Build failed:', e);
    process.exit(1)
});
